### ISSUE TITLE
계산기 별도 탭에 표시할 기능 관련

### ISSUE THREAD

**Issue by goingtofgo** [Cass07/FgoCalc#7]
계산기에 새 탭에 표시할 내용으로
_클래스별 시스템만족을 위한 최소 오버킬수 계산 (적 히든도 포함?) (column을 클래스로)_ 
라는 의견을 주셨는데요... 이게 좀 생각이 필요하더라구요

일단 문제되는게 적의 숫자입니다. 예를들어 적이 2마리일때 총 7타의 오버킬이 필요하면, 3타/4타도 가능하고 2타/5타도 가능합니다.
3마리일때 총 7타 오버킬이 가능하다면 2/2/3, 1/1/5, 1,2,4 등 수열 조합이 생기게 되는데...

이를 보여주는 방식으로는 세가지 디자인 초이스가 가능하다고 봅니다

**_1. 총 오버킬 타수와 타수 별 데미지를 함께 표시_**

![image](https://user-images.githubusercontent.com/70013544/91042976-a72f8100-e64d-11ea-8c94-088a73c20c95.png)

장점: 사용자가 필요 오버킬에 따른 에너미의 HP 가능 범위를 정확하게 계산해볼 수 있음
단점: 시스템 가능 HP 범위를 사용자가 직접 타수를 고려하여 계산이 필요함

**_2. 필요 오버킬 평균값과 그에 따른 에너미 HP를 표시_**

![image](https://user-images.githubusercontent.com/70013544/91043097-eb228600-e64d-11ea-9e5c-10c8f91ae254.png)

장점: 필요오버킬을 에너미마다 가장 고르게 나누어, 시스템이 가능한 적 HP를 자동으로 보여줌
단점: HP 12만 / HP 4만 과 같이 매우 치우친 형태의 에너미 배치에는 계산이 올바르지 않게 됨

**_3. 사용자가 직접 오버킬 타수를 분배_**
![image](https://user-images.githubusercontent.com/70013544/91043928-6cc6e380-e64f-11ea-9266-b3c6f721e083.png)

장점: 사용자가 ▲▼ 버튼을 눌러서 오버킬을 분배하고, 자동적으로 적의 체력 범위도 볼 수 있음
단점: 구현할게 많고 사용자도 좀더 할게 생김

사실 1번만으로도 하고싶은건 다 할 수 있을 것 같고...
할수만 있다면 3번이 말씀하신

> <추가>클래스별 시스템만족을 위한 최소 오버킬수 계산 (적 히든도 포함?) (column을 클래스로)
> <추가?> 보구 타수당 누적 대미지 테이블 (오버킬 횟수를 통한 대략적인 시스템 가능 범위를 보기 위해서?)

를 융합해서 하나의 표로 처리할 수 있으니 제일 좋긴 합니다.

의견 있으신가요?

개인적으로는 언젠가 3기사, 캐스터, 라이더, 버서커, 어쌔신의 오각형 그래프를 만들어서 뭔가 까리하게 표현하고 싶은 욕망도 있긴한데...... 일단 표로 보여주는것부터 완성해야겠죠 -_-

**Comment by Cass07** [comment]
난수는 어차피 어떤 상황에서건 시스템 돌아가려면 최저로 맞추는게 맞다 생각합니다. 3번 좋아보이는데..
![image](https://user-images.githubusercontent.com/15764898/91045474-e6f86780-e651-11ea-9132-09f637cf0d6f.png)
이런식으로 구현은 어떠신가요

**Comment by goingtofgo** [comment]
그... 1체에서 3체가 되면 기본 재수급이 3배가 되서 오버킬 계산을 다시해야하지 않나요?

**Comment by Cass07** [comment]
오버킬 횟수라는게 3체 기준.... 이기엔 요새 1~2체도 돌아가는군요 당연히 3체기준으로 생각했습니다 그러면 계산 전 드랍다운으로 적 수를 선택하는게 어떨까요

**Comment by goingtofgo** [comment]
네 요즘 311같은 던전이 등장하면서 전부 고려해야할 것 같습니다

시스템 가능 여부를 대략적으로 보여주고 싶어도 워낙 몹 배치가 중구난방이어서 좀 어렵지 않을까 싶기도 한데 아이디어 있으신가요?

여튼 한번에 다 표시한다면 10개의 raw에 7개의 col이 필요하겠네요... 좀 오바인거 같기도 하구...

아니면 현재 에너미 데이터 입력란에서 체력/히든속성/방깎/커깎/보구깎 다 없애버리고
에너미 체크/ 클래스 드롭다운만 남긴 후 계산버튼 누르면 (혹은 누를필요 없이 자동으로)
바로 아래에 오버킬과 오버킬 분배칸 만들어줘서 계산하게 하는건 어떨까요?

문제는... 딜러의 스킬이 적1체 지정 깎기 스킬이면 좀 계산이 복잡해지긴 하는데... 머리로만 생각하기로는 어차피 계산식 새로짜면 Handle가능할것 같기도하네요. 딜러가 1체지정 스킬 있을시 에너미 란에 체크박스 넣어주고...

**Comment by Cass07** [comment]
스까던 생각하는거면 실제 던전을 가지고 계산하겠다는건데, 그럼 걍 기존에 있던 적 데이터 입력해서 리차지량 얻는 계산탭을 쓰는게 젤 낫지 않을까요..?

**Comment by goingtofgo** [comment]
음 하긴 스까던일 경우 조합이 너무 많으니까 실제 던전 데이터 이외에는 실험하는 의미가 없긴 하겠네요.

그러면 
클래스 드롭다운 선택 방식으로 하고, 1체깎의 경우 어딘가에 체크박스를 넣는다 (만약 계산식이 불가능하면 1체깎은 지원X)
가 되겠네요

마지막으로 대략적인 시스템 여부는 5각형 그래프의 각 내각을 클래스로 해서 필요 오버킬 타수or시스템 가능 평균 적 체력을 값으로 해서 1체/2체/3체 그래프 만들어 보여주는 방식이 좋겠습니다.
